### ISSUE TITLE
Warning: HasNextMonitorAspect.aj:370 [warning] advice defined in mop.HasNextMonitorAspect

### ISSUE THREAD

**Issue by omarjaved83** [runtimeverification/javamop#218]
I compiled the source code of javamop 4.2 and when I run it, I get the following warning 

HasNextMonitorAspect.aj:370 [warning] advice defined in mop.HasNextMonitorAspect has not been applied [Xlint:adviceDidNotMatch]

How to remove this warning?

**Comment by xiaohe27** [comment]
@omarjaved83 This warning means that there is no location in your program under monitoring matches the pointcut you defined in the .mop spec; and therefore the given advice cannot be injected to the specified pointcut. To remove this warning, you can either edit the program you want to monitor by adding the method invocation that will match the pointcut (in this case, I would assume some iterator's hasNext() method); OR, you may modify the pointcut so that it refers to some existing program locations.

**Comment by omarjaved83** [comment]
Ok, but i am running examples/FSM/HasNext/HasNext_1 in Javamop. If I understood it correctly, it has a program under monitoring which invokes next() without first checking the condition of hasNext().  Is this the program being monitored or should I create a program which should match the pointcut defined? 
Thank you.

**Comment by xiaohe27** [comment]
@omarjaved83 If I remembered correctly, there are two pointcuts defined in that spec: one for hasNext() and one for next(). So if the sample program only invokes next() but does not call hasNext(), then only the advice for next() can be injected; the advice for hasNext() is not able to be injected in the specified position because there is no invocation of hasNext() in the program, that should explain why the advice cannot be applied. For the HasNext_1.java, even if you add one invocation of hasNext() before the four consecutive invocations of next(), the property is still violated but you'll be able to eliminate the warning.

**Comment by omarjaved83** [comment]
OK got it.  It makes sense now. Thanks.
